FROM python:3.14-slim-bookworm 
RUN apt-get update && apt-get install -y curl
RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
    && apt-get install -y nodejs \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
WORKDIR /app
COPY . .
RUN pip3 install -r requirements.txt
# con bash debe iniciar el contenedor con terminal interativa
CMD ["tail", "-f", "/dev/null"]